# Generated by Django 5.0.1 on 2024-09-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0003_alter_user_email_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
