# Generated by Django 5.0.1 on 2024-09-04 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0006_alter_usermodel_options_alter_usermodel_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='phone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
