# Generated by Django 5.0.1 on 2024-09-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heart', '0008_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='phone',
        ),
    ]
